// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_area1tempLabel = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_area1timeLabel1 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_area1tempLabel2 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_area1timeLabel2 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_area1tempLabel3 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_area1timeLabel3 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_area1tempLabel4 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_area1timeLabel4 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel5, 299);
    lv_obj_set_height(ui_Panel5, 53);
    lv_obj_set_x(ui_Panel5, -161);
    lv_obj_set_y(ui_Panel5, -197);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 30);
    lv_obj_set_y(ui_Label56, 0);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "Area display");
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 402);
    lv_obj_set_height(ui_Container18, 308);
    lv_obj_set_x(ui_Container18, 2);
    lv_obj_set_y(ui_Container18, 18);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container18, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container18, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Container18);
    lv_obj_set_width(ui_Panel1, 171);
    lv_obj_set_height(ui_Panel1, 114);
    lv_obj_set_x(ui_Panel1, -118);
    lv_obj_set_y(ui_Panel1, -115);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 137);
    lv_obj_set_height(ui_Container10, 39);
    lv_obj_set_x(ui_Container10, -113);
    lv_obj_set_y(ui_Container10, 31);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1tempLabel = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_area1tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1tempLabel, -7);
    lv_obj_set_y(ui_area1tempLabel, 16);
    lv_obj_set_align(ui_area1tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1tempLabel, "180");
    lv_obj_set_style_text_font(ui_area1tempLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -7);
    lv_obj_set_y(ui_Label41, 16);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "°C");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 137);
    lv_obj_set_height(ui_Container11, 39);
    lv_obj_set_x(ui_Container11, -138);
    lv_obj_set_y(ui_Container11, 67);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1timeLabel1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_area1timeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1timeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1timeLabel1, -7);
    lv_obj_set_y(ui_area1timeLabel1, 16);
    lv_obj_set_align(ui_area1timeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1timeLabel1, "20");
    lv_obj_set_style_text_font(ui_area1timeLabel1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -7);
    lv_obj_set_y(ui_Label43, 16);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "min");
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container18);
    lv_obj_set_width(ui_Panel2, 171);
    lv_obj_set_height(ui_Panel2, 114);
    lv_obj_set_x(ui_Panel2, -118);
    lv_obj_set_y(ui_Panel2, -115);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x0072FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 137);
    lv_obj_set_height(ui_Container12, 39);
    lv_obj_set_x(ui_Container12, -113);
    lv_obj_set_y(ui_Container12, 31);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1tempLabel2 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_area1tempLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1tempLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1tempLabel2, -7);
    lv_obj_set_y(ui_area1tempLabel2, 16);
    lv_obj_set_align(ui_area1tempLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1tempLabel2, "180");
    lv_obj_set_style_text_font(ui_area1tempLabel2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -7);
    lv_obj_set_y(ui_Label45, 16);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "°C");
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 137);
    lv_obj_set_height(ui_Container13, 39);
    lv_obj_set_x(ui_Container13, -138);
    lv_obj_set_y(ui_Container13, 67);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1timeLabel2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_area1timeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1timeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1timeLabel2, -7);
    lv_obj_set_y(ui_area1timeLabel2, 16);
    lv_obj_set_align(ui_area1timeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1timeLabel2, "20");
    lv_obj_set_style_text_font(ui_area1timeLabel2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -7);
    lv_obj_set_y(ui_Label47, 16);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "min");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Container18);
    lv_obj_set_width(ui_Panel3, 171);
    lv_obj_set_height(ui_Panel3, 114);
    lv_obj_set_x(ui_Panel3, -118);
    lv_obj_set_y(ui_Panel3, -115);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x83FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 137);
    lv_obj_set_height(ui_Container14, 39);
    lv_obj_set_x(ui_Container14, -113);
    lv_obj_set_y(ui_Container14, 31);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1tempLabel3 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_area1tempLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1tempLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1tempLabel3, -7);
    lv_obj_set_y(ui_area1tempLabel3, 16);
    lv_obj_set_align(ui_area1tempLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1tempLabel3, "180");
    lv_obj_set_style_text_font(ui_area1tempLabel3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -7);
    lv_obj_set_y(ui_Label49, 16);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "°C");
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 137);
    lv_obj_set_height(ui_Container15, 39);
    lv_obj_set_x(ui_Container15, -138);
    lv_obj_set_y(ui_Container15, 67);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1timeLabel3 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_area1timeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1timeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1timeLabel3, -7);
    lv_obj_set_y(ui_area1timeLabel3, 16);
    lv_obj_set_align(ui_area1timeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1timeLabel3, "20");
    lv_obj_set_style_text_font(ui_area1timeLabel3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -7);
    lv_obj_set_y(ui_Label51, 16);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "min");
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Container18);
    lv_obj_set_width(ui_Panel4, 171);
    lv_obj_set_height(ui_Panel4, 114);
    lv_obj_set_x(ui_Panel4, -118);
    lv_obj_set_y(ui_Panel4, -115);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container16 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 137);
    lv_obj_set_height(ui_Container16, 39);
    lv_obj_set_x(ui_Container16, -113);
    lv_obj_set_y(ui_Container16, 31);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_area1tempLabel4 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_area1tempLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1tempLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1tempLabel4, -7);
    lv_obj_set_y(ui_area1tempLabel4, 16);
    lv_obj_set_align(ui_area1tempLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1tempLabel4, "180");
    lv_obj_set_style_text_font(ui_area1tempLabel4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -7);
    lv_obj_set_y(ui_Label53, 16);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "°C");
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 137);
    lv_obj_set_height(ui_Container17, 39);
    lv_obj_set_x(ui_Container17, -138);
    lv_obj_set_y(ui_Container17, 67);
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container17, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label54 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -7);
    lv_obj_set_y(ui_Label54, 16);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "20");
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_area1timeLabel4 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_area1timeLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_area1timeLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_area1timeLabel4, -7);
    lv_obj_set_y(ui_area1timeLabel4, 16);
    lv_obj_set_align(ui_area1timeLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_area1timeLabel4, "min");
    lv_obj_set_style_text_font(ui_area1timeLabel4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel5 = NULL;
    ui_Label56 = NULL;
    ui_Container18 = NULL;
    ui_Panel1 = NULL;
    ui_Container10 = NULL;
    ui_area1tempLabel = NULL;
    ui_Label41 = NULL;
    ui_Container11 = NULL;
    ui_area1timeLabel1 = NULL;
    ui_Label43 = NULL;
    ui_Panel2 = NULL;
    ui_Container12 = NULL;
    ui_area1tempLabel2 = NULL;
    ui_Label45 = NULL;
    ui_Container13 = NULL;
    ui_area1timeLabel2 = NULL;
    ui_Label47 = NULL;
    ui_Panel3 = NULL;
    ui_Container14 = NULL;
    ui_area1tempLabel3 = NULL;
    ui_Label49 = NULL;
    ui_Container15 = NULL;
    ui_area1timeLabel3 = NULL;
    ui_Label51 = NULL;
    ui_Panel4 = NULL;
    ui_Container16 = NULL;
    ui_area1tempLabel4 = NULL;
    ui_Label53 = NULL;
    ui_Container17 = NULL;
    ui_Label54 = NULL;
    ui_area1timeLabel4 = NULL;

}
