// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_area1tempLabel;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_area1timeLabel1;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_area1tempLabel2;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_area1timeLabel2;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_area1tempLabel3;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_area1timeLabel3;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_area1tempLabel4;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_area1timeLabel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

