// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#include "../ui.h"
#include "app.h"
lv_obj_t *ui_Screen5 = NULL;
lv_obj_t *ui_Container19 = NULL;
lv_obj_t *ui_Panel6 = NULL;
lv_obj_t *ui_PotLabel = NULL;
lv_obj_t *ui_Panel9 = NULL;
lv_obj_t *ui_CookerDisplayTempLabel = NULL;
lv_obj_t *ui_Panel10 = NULL;
lv_obj_t *ui_CookerDisplayPowerLabel = NULL;
lv_obj_t *ui_Panel11 = NULL;
lv_obj_t *ui_Label25 = NULL;
lv_obj_t *ui_Container21 = NULL;
lv_obj_t *ui_Button1 = NULL;
lv_obj_t *ui_Label28 = NULL;
lv_obj_t *ui_Panel12 = NULL;
lv_obj_t *ui_CookModeNameLabel = NULL;
lv_obj_t *ui_Panel13 = NULL;
lv_obj_t *ui_CookModeNameLabelTime = NULL;
lv_obj_t *ui_Panel14 = NULL;
lv_obj_t *ui_CookModeNameLabelPower = NULL;
lv_obj_t *ui_Switch1 = NULL;
lv_obj_t *ui_Label39 = NULL;
lv_obj_t *ui_TimeLabel = NULL;
lv_obj_t *ui_VoltLabel = NULL;
static ui_msg_t msg;

// event funtions
static induction_cooking_recipes_t cur_recipe = 0;
void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {

        _ui_label_set_property(ui_CookModeNameLabel, _UI_LABEL_PROPERTY_TEXT, recipe_name[cur_recipe++]);
        if (cur_recipe == MODE_INDUCTION_MAX)
            cur_recipe = MODE_KEEP_WARM;
        msg.widget_id = WIDGET_INDUCTION_COOKING_MODE;
        msg.event = EVT_AIR_FRY_MOED_CHANGE;
        msg.value = cur_recipe;
        rt_mq_send(&env.msg_queue, &msg, sizeof(msg));
        rt_event_send(&env.ui_event, EVENT_MOTOR_WORK | EVENT_PLAY_AUDIO);
    }
}

void ui_event_Switch1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_checked_set_text_value(ui_Label39, target, "ON", "OFF");
        msg.widget_id = WIDGET_INDUCTION_COOKING_START;

        rt_mq_send(&env.msg_queue, &msg, sizeof(msg));
        if (lv_obj_has_state(target, LV_STATE_CHECKED))
        {
            msg.event = EVT_INDUCTION_COOKING_ON;
            msg.value = 1;
        }

        else
        {
            msg.event = EVT_INDUCTION_COOKING_OFF;
            msg.value = 2;
        }

        rt_mq_send(&env.msg_queue, &msg, sizeof(msg));

        rt_event_send(&env.ui_event, EVENT_MOTOR_WORK);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Container19 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 440);
    lv_obj_set_height(ui_Container19, 61);
    lv_obj_set_x(ui_Container19, 4);
    lv_obj_set_y(ui_Container19, -138);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Panel6 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel6, 118);
    lv_obj_set_height(ui_Panel6, 50);
    lv_obj_set_x(ui_Panel6, -158);
    lv_obj_set_y(ui_Panel6, -159);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_PotLabel = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_PotLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PotLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_PotLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PotLabel, "No Pot");
    lv_obj_set_style_text_font(ui_PotLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel9, 136);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_x(ui_Panel9, -24);
    lv_obj_set_y(ui_Panel9, -159);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x0064FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookerDisplayTempLabel = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_CookerDisplayTempLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CookerDisplayTempLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_CookerDisplayTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookerDisplayTempLabel, "25 °C");
    lv_obj_set_style_text_color(ui_CookerDisplayTempLabel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CookerDisplayTempLabel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CookerDisplayTempLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel10, 149);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_x(ui_Panel10, 115);
    lv_obj_set_y(ui_Panel10, -158);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFF0027), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookerDisplayPowerLabel = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_CookerDisplayPowerLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CookerDisplayPowerLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_CookerDisplayPowerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookerDisplayPowerLabel, "1000 W");
    lv_obj_set_style_text_color(ui_CookerDisplayPowerLabel, lv_color_hex(0xF9F4F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CookerDisplayPowerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CookerDisplayPowerLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel11, 478);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_x(ui_Panel11, 3);
    lv_obj_set_y(ui_Panel11, -210);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xA4A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label25, -16);
    lv_obj_set_y(ui_Label25, 1);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Induction Cooker");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 426);
    lv_obj_set_height(ui_Container21, 171);
    lv_obj_set_x(ui_Container21, -3);
    lv_obj_set_y(ui_Container21, 9);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Button1 = lv_btn_create(ui_Container21);
    lv_obj_set_width(ui_Button1, 194);
    lv_obj_set_height(ui_Button1, 167);
    lv_obj_set_x(ui_Button1, -106);
    lv_obj_set_y(ui_Button1, 10);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Label28 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "CHANGE \nMODE");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Container21);
    lv_obj_set_width(ui_Panel12, 200);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_CookModeNameLabel = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_CookModeNameLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CookModeNameLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_CookModeNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookModeNameLabel, "NAME");
    lv_obj_set_style_text_font(ui_CookModeNameLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Container21);
    lv_obj_set_width(ui_Panel13, 200);
    lv_obj_set_height(ui_Panel13, 50);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_CookModeNameLabelTime = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_CookModeNameLabelTime, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CookModeNameLabelTime, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_CookModeNameLabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookModeNameLabelTime, "TIME");
    lv_obj_set_style_text_color(ui_CookModeNameLabelTime, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CookModeNameLabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CookModeNameLabelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Container21);
    lv_obj_set_width(ui_Panel14, 200);
    lv_obj_set_height(ui_Panel14, 50);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_CookModeNameLabelPower = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_CookModeNameLabelPower, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CookModeNameLabelPower, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_CookModeNameLabelPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookModeNameLabelPower, "POWER");
    lv_obj_set_style_text_color(ui_CookModeNameLabelPower, lv_color_hex(0xFF003F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CookModeNameLabelPower, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CookModeNameLabelPower, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Switch1, 120);
    lv_obj_set_height(ui_Switch1, 55);
    lv_obj_set_x(ui_Switch1, -14);
    lv_obj_set_y(ui_Switch1, 161);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Label39 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label39, 107);
    lv_obj_set_y(ui_Label39, 162);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "OFF");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_TimeLabel, -10);
    lv_obj_set_y(ui_TimeLabel, -97);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "10:30:00");
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_VoltLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_VoltLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_VoltLabel, 143);
    lv_obj_set_y(ui_VoltLabel, -97);
    lv_obj_set_align(ui_VoltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltLabel, "4.5 | 3.7V");
    lv_obj_set_style_text_font(ui_VoltLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
}

void ui_Screen5_screen_destroy(void)
{
    if (ui_Screen5)
        lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Container19 = NULL;
    ui_Panel6 = NULL;
    ui_PotLabel = NULL;
    ui_Panel9 = NULL;
    ui_CookerDisplayTempLabel = NULL;
    ui_Panel10 = NULL;
    ui_CookerDisplayPowerLabel = NULL;
    ui_Panel11 = NULL;
    ui_Label25 = NULL;
    ui_Container21 = NULL;
    ui_Button1 = NULL;
    ui_Label28 = NULL;
    ui_Panel12 = NULL;
    ui_CookModeNameLabel = NULL;
    ui_Panel13 = NULL;
    ui_CookModeNameLabelTime = NULL;
    ui_Panel14 = NULL;
    ui_CookModeNameLabelPower = NULL;
    ui_Switch1 = NULL;
    ui_Label39 = NULL;
    ui_TimeLabel = NULL;
    ui_VoltLabel = NULL;
}
