// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_CurTimeLabel;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_SetTimeLabel;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern void ui_event_TimeAdd2(lv_event_t * e);
extern lv_obj_t * ui_TimeAdd2;
extern lv_obj_t * ui_Label33;
extern void ui_event_TimeSub2(lv_event_t * e);
extern lv_obj_t * ui_TimeSub2;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label58;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

