// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_xaxisLabel6;
extern lv_obj_t * ui_xaxisLabel7;
extern lv_obj_t * ui_xaxisLabel8;
extern lv_obj_t * ui_xaxisLabel9;
extern lv_obj_t * ui_xaxisLabel10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

