// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#include "../ui.h"
#include "app.h"
lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Panel1 = NULL;
lv_obj_t *ui_Panel2 = NULL;
lv_obj_t *ui_Panel8 = NULL;
lv_obj_t *ui_Label15 = NULL;
lv_obj_t *ui_Container1 = NULL;
lv_obj_t *ui_ButtonChips = NULL;
lv_obj_t *ui_Label3 = NULL;
lv_obj_t *ui_Container2 = NULL;
lv_obj_t *ui_humidityLabel = NULL;
lv_obj_t *ui_Label16 = NULL;
lv_obj_t *ui_paLabel = NULL;
lv_obj_t *ui_Label17 = NULL;
lv_obj_t *ui_tempLabel = NULL;
lv_obj_t *ui_Label18 = NULL;
lv_obj_t *ui_Slider1 = NULL;
lv_obj_t *ui_Label12 = NULL;
lv_obj_t *ui_Label13 = NULL;
lv_obj_t *ui_Label10 = NULL;
lv_obj_t *ui_TempAdd = NULL;
lv_obj_t *ui_Label4 = NULL;
lv_obj_t *ui_TempSub = NULL;
lv_obj_t *ui_Label5 = NULL;
lv_obj_t *ui_Label14 = NULL;
lv_obj_t *ui_Label11 = NULL;
lv_obj_t *ui_Slider2 = NULL;
lv_obj_t *ui_Label9 = NULL;
lv_obj_t *ui_TimeAdd = NULL;
lv_obj_t *ui_Label6 = NULL;
lv_obj_t *ui_TimeSub = NULL;
lv_obj_t *ui_Label7 = NULL;
lv_obj_t *ui_Container4 = NULL;
lv_obj_t *ui_Switch2 = NULL;
lv_obj_t *ui_Label8 = NULL;

static ui_msg_t msg;
static recipes_t cur_recipe = 0;
// event funtions
void ui_event_Screen1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_ButtonChips(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_label_set_property(ui_Label15, _UI_LABEL_PROPERTY_TEXT, recipe_name[cur_recipe++]);
        if (cur_recipe == MODE_MAX)
            cur_recipe = MODE_CHIPS;
        msg.widget_id = WIDGET_AIR_FRY_MODE;
        msg.event = EVT_AIR_FRY_MOED_CHANGE;
        msg.value = cur_recipe;
        _ui_slider_set_property(ui_Slider1, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, cooking_table[cur_recipe].area_temp[0]);
        _ui_slider_set_property(ui_Slider2, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, cooking_table[cur_recipe].area_time[0]);
        _ui_slider_set_text_value(ui_Label12, ui_Slider1, "", "");
        _ui_slider_set_text_value(ui_Label11, ui_Slider2, "", "");
        rt_mq_send(&env.msg_queue, &msg, sizeof(msg));
    }
}

void ui_event_Slider1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_slider_set_text_value(ui_Label12, target, "", "");
    }
}

void ui_event_TempAdd(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_slider_increment(ui_Slider1, 10, LV_ANIM_ON);
    }
}

void ui_event_TempSub(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_slider_increment(ui_Slider1, -10, LV_ANIM_ON);
    }
}

void ui_event_Slider2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_slider_set_text_value(ui_Label11, target, "", "");
    }
}

void ui_event_TimeAdd(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_slider_increment(ui_Slider2, 5, LV_ANIM_ON);
    }
}

void ui_event_TimeSub(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_slider_increment(ui_Slider2, -5, LV_ANIM_ON);
    }
}

void ui_event_Switch2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_checked_set_text_value(ui_Label8, target, "ON", "OFF");
        msg.widget_id = WIDGET_AIR_FRY_START;
        msg.value = lv_slider_get_value(target);

        if (lv_obj_has_state(target, LV_STATE_CHECKED))
            msg.event = EVT_AIR_FRY_ON;
        else
            msg.event = EVT_AIR_FRY_OFF;
        rt_mq_send(&env.msg_queue, &msg, sizeof(msg));
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_CHECKABLE);    /// Flags
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 447);
    lv_obj_set_height(ui_Panel1, 90);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, -102);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 447);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, -2);
    lv_obj_set_y(ui_Panel2, 20);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 299);
    lv_obj_set_height(ui_Panel8, 53);
    lv_obj_set_x(ui_Panel8, -161);
    lv_obj_set_y(ui_Panel8, -197);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label15, 38);
    lv_obj_set_y(ui_Label15, -4);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "mode_name");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 287);
    lv_obj_set_height(ui_Container1, 143);
    lv_obj_set_x(ui_Container1, 123);
    lv_obj_set_y(ui_Container1, -198);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ButtonChips = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_ButtonChips, 154);
    lv_obj_set_height(ui_ButtonChips, 50);
    lv_obj_set_x(ui_ButtonChips, 293);
    lv_obj_set_y(ui_ButtonChips, -175);
    lv_obj_set_align(ui_ButtonChips, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonChips, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonChips, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_ButtonChips, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ButtonChips);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -4);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Recipe");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 138);
    lv_obj_set_height(ui_Container2, 97);
    lv_obj_set_x(ui_Container2, -130);
    lv_obj_set_y(ui_Container2, 146);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_Container2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_humidityLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_humidityLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_humidityLabel, -162);
    lv_obj_set_y(ui_humidityLabel, 161);
    lv_obj_set_align(ui_humidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityLabel, "26.5");

    ui_Label16 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label16, -128);
    lv_obj_set_y(ui_Label16, 148);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "   °C");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_paLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_paLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_paLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_paLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_paLabel, "101.1");

    ui_Label17 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label17, -128);
    lv_obj_set_y(ui_Label17, 177);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "  kPa");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tempLabel, -199);
    lv_obj_set_y(ui_tempLabel, 162);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "45.1");

    ui_Label18 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label18, -130);
    lv_obj_set_y(ui_Label18, 210);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "  %");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 60, 200);
    lv_slider_set_value(ui_Slider1, 60, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_Slider1, 60, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 157);
    lv_obj_set_height(ui_Slider1, 18);
    lv_obj_set_x(ui_Slider1, 49);
    lv_obj_set_y(ui_Slider1, -126);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xCAC3C3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0xFF002C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label12, -157);
    lv_obj_set_y(ui_Label12, -122);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "60");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label13, -116);
    lv_obj_set_y(ui_Label13, -121);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "°C");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label10, -132);
    lv_obj_set_y(ui_Label10, -80);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "TEMP");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempAdd = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_TempAdd, 50);
    lv_obj_set_height(ui_TempAdd, 45);
    lv_obj_set_x(ui_TempAdd, -5);
    lv_obj_set_y(ui_TempAdd, -87);
    lv_obj_set_align(ui_TempAdd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempAdd, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_TempAdd, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_TempAdd, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempAdd, lv_color_hex(0x0086FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempAdd, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_TempAdd);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "+");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSub = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_TempSub, 50);
    lv_obj_set_height(ui_TempSub, 45);
    lv_obj_set_x(ui_TempSub, 104);
    lv_obj_set_y(ui_TempSub, -87);
    lv_obj_set_align(ui_TempSub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempSub, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_TempSub, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_TempSub, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempSub, lv_color_hex(0x0086FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSub, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TempSub);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "-");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label14, -106);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "min");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label11, -162);
    lv_obj_set_y(ui_Label11, 4);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "10");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider2, 10, 60);
    lv_slider_set_value(ui_Slider2, 10, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_Slider2, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 157);
    lv_obj_set_height(ui_Slider2, 18);
    lv_obj_set_x(ui_Slider2, 50);
    lv_obj_set_y(ui_Slider2, -5);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xDCD9DC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0x3600FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x0F0303), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label9, -130);
    lv_obj_set_y(ui_Label9, 42);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "TIME");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeAdd = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_TimeAdd, 50);
    lv_obj_set_height(ui_TimeAdd, 45);
    lv_obj_set_x(ui_TimeAdd, -5);
    lv_obj_set_y(ui_TimeAdd, 32);
    lv_obj_set_align(ui_TimeAdd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeAdd, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_TimeAdd, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_TimeAdd, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeAdd, lv_color_hex(0x0086FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAdd, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_TimeAdd);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeSub = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_TimeSub, 50);
    lv_obj_set_height(ui_TimeSub, 45);
    lv_obj_set_x(ui_TimeSub, 108);
    lv_obj_set_y(ui_TimeSub, 32);
    lv_obj_set_align(ui_TimeSub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeSub, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_TimeSub, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_TimeSub, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeSub, lv_color_hex(0x0086FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeSub, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_TimeSub);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "-");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 150);
    lv_obj_set_height(ui_Container4, 64);
    lv_obj_set_x(ui_Container4, 55);
    lv_obj_set_y(ui_Container4, 157);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Switch2 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_Switch2, 83);
    lv_obj_set_height(ui_Switch2, 40);
    lv_obj_set_x(ui_Switch2, 42);
    lv_obj_set_y(ui_Switch2, 191);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label8, 162);
    lv_obj_set_y(ui_Label8, 197);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "OFF");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonChips, ui_event_ButtonChips, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempAdd, ui_event_TempAdd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempSub, ui_event_TempSub, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeAdd, ui_event_TimeAdd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeSub, ui_event_TimeSub, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel8 = NULL;
    ui_Label15 = NULL;
    ui_Container1 = NULL;
    ui_ButtonChips = NULL;
    ui_Label3 = NULL;
    ui_Container2 = NULL;
    ui_humidityLabel = NULL;
    ui_Label16 = NULL;
    ui_paLabel = NULL;
    ui_Label17 = NULL;
    ui_tempLabel = NULL;
    ui_Label18 = NULL;
    ui_Slider1 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label10 = NULL;
    ui_TempAdd = NULL;
    ui_Label4 = NULL;
    ui_TempSub = NULL;
    ui_Label5 = NULL;
    ui_Label14 = NULL;
    ui_Label11 = NULL;
    ui_Slider2 = NULL;
    ui_Label9 = NULL;
    ui_TimeAdd = NULL;
    ui_Label6 = NULL;
    ui_TimeSub = NULL;
    ui_Label7 = NULL;
    ui_Container4 = NULL;
    ui_Switch2 = NULL;
    ui_Label8 = NULL;
}
