// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: magic_biscuit_v1_1

#ifndef _MAGIC_BISCUIT_V1_1_UI_H
#define _MAGIC_BISCUIT_V1_1_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

    ///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"

    ///////////////////// VARIABLES ////////////////////

    // EVENTS

    extern lv_obj_t *ui____initial_actions0;

    // UI INIT
    void ui_init(void);
    void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
